import type { PaginatedResponse, PaginationQuery } from '@hotel-growth-os/shared';
export type { PaginatedResponse, PaginationQuery };
export type ListParams = PaginationQuery & Record<string, unknown>;
export const getEntityId = (entity: { _id?: string; id?: string }): string => entity.id || entity._id || '';

export interface AuditLogEntry { _id: string; id?: string; action: string; entity?: string; createdAt: string; changes?: Record<string, unknown>; userId?: { name?: string; email?: string }; }
export interface User { id: string; _id?: string; name: string; email: string; phone?: string; role: string; hotelId?: string; lastLoginAt?: string; }
export interface AuthResponse { user: User; token: string; }
export interface Hotel { _id: string; id?: string; name: string; slug?: string; email?: string; phone?: string; isActive?: boolean; settings?: Record<string, unknown>; createdAt?: string; updatedAt?: string; }
export interface GuestDocument { _id?: string; id?: string; url: string; publicId?: string; documentType?: string; uploadedAt?: string; }
export interface Guest { _id: string; id?: string; fullName?: string; name: string; firstName?: string; lastName?: string; phone: string; alternatePhone?: string; email?: string; gender?: string; dateOfBirth?: string; anniversaryDate?: string; city?: string; state?: string; country?: string; address?: string; idProofType?: string; idProofNumber?: string; idProofImages?: GuestDocument[]; profileImage?: string; guestType?: string; source?: string; preferences?: string[]; foodPreference?: string; roomPreference?: string; specialRequests?: string; tags?: string[]; notes?: string; totalBookings?: number; completedBookings?: number; cancelledBookings?: number; noShowCount?: number; totalSpend?: number; averageSpend?: number; lastBookingDate?: string; lastStayDate?: string; lastEnquiryDate?: string; lastReviewRating?: number; visitCount?: number; lastVisitAt?: string; isRepeatGuest?: boolean; isVip?: boolean; isBlacklisted?: boolean; blacklistReason?: string; loyaltyPoints?: number; marketingConsent?: boolean; whatsappConsent?: boolean; emailConsent?: boolean; metadata?: Record<string, unknown>; createdAt?: string; updatedAt?: string; auditLogs?: AuditLogEntry[]; }
export interface GuestStats { totalGuests: number; newGuestsThisMonth: number; repeatGuests: number; vipGuests: number; blacklistedGuests: number; birthdayThisMonth: number; anniversaryThisMonth: number; topCities: Record<string, number>; topSpendingGuests: Array<{ id: string; fullName: string; totalSpend: number }>; guestsWithNoBooking: number; campaignEligible: number; }
export interface GuestFormData { fullName: string; phone: string; alternatePhone?: string; email?: string; gender?: string; dateOfBirth?: string; anniversaryDate?: string; city?: string; state?: string; country?: string; address?: string; guestType?: string; source?: string; foodPreference?: string; roomPreference?: string; specialRequests?: string; tags?: string[]; notes?: string; marketingConsent?: boolean; whatsappConsent?: boolean; emailConsent?: boolean; isVip?: boolean; }
export interface GuestHistory { guest: Guest; bookings: Booking[]; enquiries: Enquiry[]; payments: Payment[]; reviews: Review[]; campaigns: unknown[]; whatsappMessages: unknown[]; whatsappSummary?: { totalMessages: number; incoming: number; outgoing: number; lastMessageAt?: string }; auditLogs?: AuditLogEntry[]; summary: { totalSpend: number; totalBookings: number; completedBookings: number; cancelledBookings: number; noShowCount: number; isRepeatGuest: boolean }; }
export interface Staff { _id: string; id?: string; userId?: string; hotelId?: string; fullName: string; name?: string; email: string; phone: string; alternatePhone?: string; role: string; department?: string; designation?: string; profileImage?: string; gender?: string; dateOfBirth?: string; joiningDate?: string; salary?: number; shiftType?: string; shiftStartTime?: string; shiftEndTime?: string; address?: string; emergencyContactName?: string; emergencyContactPhone?: string; permissions?: string[]; password?: string; status?: string; isActive?: boolean; lastLoginAt?: string; createdAt?: string; updatedAt?: string; auditLogs?: AuditLogEntry[]; }
export interface StaffStats { total: number; active: number; inactive: number; suspended: number; byRole: Record<string, number>; byDepartment: Record<string, number>; }
export interface RoomTypeImage { _id?: string; id?: string; url: string; publicId?: string; altText?: string; sortOrder?: number; }
export interface RoomType { _id: string; id?: string; name: string; slug?: string; code?: string; description?: string; shortDescription?: string; basePrice: number; weekdayPrice?: number; weekendPrice?: number; extraAdultPrice?: number; extraChildPrice?: number; taxPercentage?: number; discountPercentage?: number; maxGuests: number; maxAdults?: number; maxChildren?: number; bedType?: string; roomSize?: number; roomSizeUnit?: string; totalRooms?: number; amenities?: string[]; facilities?: string[]; images?: RoomTypeImage[]; coverImage?: string; cancellationPolicy?: string; checkInInstructions?: string; mealPlan?: string; inventoryType?: string; status?: string; isAvailableForBooking?: boolean; isVisibleOnWebsite?: boolean; sortOrder?: number; tags?: string[]; metadata?: Record<string, unknown>; isActive?: boolean; createdAt?: string; updatedAt?: string; auditLogs?: AuditLogEntry[]; linkedRoomsCount?: number; }
export interface Room { [key: string]: unknown; _id: string; id?: string; roomNumber: string; floor?: number; floorNumber?: number; roomTypeId?: string | RoomType; status: string; housekeepingStatus?: string; maintenanceStatus?: string; isBookable?: boolean; isBlocked?: boolean; blockedReason?: string; currentGuestId?: string | Guest; currentBookingId?: string | { bookingNumber?: string; _id?: string; id?: string }; buildingName?: string; wing?: string; roomName?: string; description?: string; notes?: string; tags?: string[]; priceOverride?: number; maxGuestsOverride?: number; isPriceOverridden?: boolean; isVisibleToStaff?: boolean; createdAt?: string; auditLogs?: AuditLogEntry[]; }
export interface RoomStats { totalRooms: number; availableRooms: number; occupiedRooms: number; reservedRooms?: number; dirtyRooms: number; cleaningRooms: number; maintenanceRooms: number; blockedRooms: number; outOfOrderRooms: number; occupancyPercentage: number; roomTypeWiseCount?: Record<string, number>; floorWiseCount?: Record<string, number>; housekeepingSummary?: Record<string, number>; }
export interface RoomFormData { roomNumber: string; roomTypeId?: string; floorNumber?: number; floor?: number; buildingName?: string; wing?: string; roomName?: string; description?: string; status?: string; housekeepingStatus?: string; maintenanceStatus?: string; isBookable?: boolean; isBlocked?: boolean; notes?: string; tags?: string[]; priceOverride?: number; maxGuestsOverride?: number; isPriceOverridden?: boolean; isVisibleToStaff?: boolean; }
export interface BulkRoomFormData { roomTypeId: string; floorNumber?: number; startNumber?: number; count?: number; startRoomNumber?: number; endRoomNumber?: number; prefix?: string; buildingName?: string; wing?: string; }
export interface AvailableRoom extends Room { roomType?: RoomType; effectivePrice: number; effectiveMaxGuests: number; }
export interface Enquiry { _id: string; id?: string; guestName: string; phone: string; email?: string; source: string; status: string; checkInDate?: string; checkOutDate?: string; notes?: string; createdAt?: string; }
export interface Booking { _id: string; id?: string; bookingNumber: string; guestId: string | Guest; status: string; paymentStatus: string; checkInDate: string; checkOutDate: string; totalAmount: number; paidAmount: number; adults?: number; children?: number; createdAt?: string; }
export interface Payment { _id: string; id?: string; bookingId: string | Booking; guestId?: string | Guest; amount: number; method: string; status: string; reference?: string; notes?: string; paidAt?: string; createdAt?: string; }
export interface Review { _id: string; id?: string; guestId?: string | Guest; bookingId?: string; rating?: number; feedback?: string; status?: string; createdAt?: string; }
export interface Campaign { _id: string; id?: string; name: string; type: string; status: string; message?: string; createdAt?: string; }
export interface GenericEntity { _id: string; id?: string; [key: string]: unknown; }

export interface RoomTypeFormData { name: string; code?: string; description?: string; shortDescription?: string; basePrice: number; weekdayPrice?: number; weekendPrice?: number; extraAdultPrice?: number; extraChildPrice?: number; taxPercentage?: number; discountPercentage?: number; maxGuests: number; maxAdults?: number; maxChildren?: number; bedType?: string; roomSize?: number; roomSizeUnit?: string; totalRooms?: number; amenities?: string[]; facilities?: string[]; coverImage?: string; cancellationPolicy?: string; checkInInstructions?: string; mealPlan?: string; inventoryType?: string; status?: string; isAvailableForBooking?: boolean; isVisibleOnWebsite?: boolean; sortOrder?: number; tags?: string[]; metadata?: Record<string, unknown>; isActive?: boolean; }
export interface RoomTypeStats { [key: string]: number | Record<string, number> | undefined; totalRoomTypes: number; activeRoomTypes: number; inactiveRoomTypes: number; bookableRoomTypes?: number; websiteVisibleRoomTypes?: number; visibleOnWebsite?: number; availableForBooking?: number; averageBasePrice: number; totalRooms?: number; roomTypesWithoutImages?: number; amenityUsage?: Record<string, number>; }
export interface StaffFormData { fullName: string; email: string; phone: string; alternatePhone?: string; role: string; department?: string; designation?: string; gender?: string; dateOfBirth?: string; joiningDate?: string; salary?: number; shiftType?: string; shiftStartTime?: string; shiftEndTime?: string; address?: string; emergencyContactName?: string; emergencyContactPhone?: string; permissions?: string[]; password?: string; status?: string; }
