import { Router } from 'express';
import { authMiddleware } from '../../middlewares/authMiddleware';
import { hotelAccessMiddleware } from '../../middlewares/hotelAccessMiddleware';
import { roleMiddleware } from '../../middlewares/roleMiddleware';
import { validate } from '../../validations/validate';
import { assignSchema, convertToBookingSchema, createSchema, idParamSchema, listQuerySchema, noteSchema, statusSchema, updateSchema } from './enquiries.validation';
import * as controller from './enquiries.controller';

const router = Router();
const enquiryRoles = ['super_admin', 'hotel_owner', 'hotel_manager', 'reception_staff', 'sales_staff'] as const;
router.use(authMiddleware, hotelAccessMiddleware);
router.get('/stats', roleMiddleware(...enquiryRoles), controller.stats);
router.get('/', roleMiddleware(...enquiryRoles), validate(listQuerySchema, 'query'), controller.list);
router.post('/', roleMiddleware(...enquiryRoles), validate(createSchema), controller.create);
router.patch('/:id/assign', validate(idParamSchema, 'params'), roleMiddleware(...enquiryRoles), validate(assignSchema), controller.assign);
router.patch('/:id/status', validate(idParamSchema, 'params'), roleMiddleware(...enquiryRoles), validate(statusSchema), controller.updateStatus);
router.patch('/:id/notes', validate(idParamSchema, 'params'), roleMiddleware(...enquiryRoles), validate(noteSchema), controller.addNote);
router.post('/:id/convert/lead', validate(idParamSchema, 'params'), roleMiddleware(...enquiryRoles), controller.convertToLead);
router.post('/:id/convert/guest', validate(idParamSchema, 'params'), roleMiddleware(...enquiryRoles), controller.convertToGuest);
router.post('/:id/convert/booking', validate(idParamSchema, 'params'), roleMiddleware(...enquiryRoles), validate(convertToBookingSchema), controller.convertToBooking);
router.get('/:id', roleMiddleware(...enquiryRoles), validate(idParamSchema, 'params'), controller.getById);
router.patch('/:id', validate(idParamSchema, 'params'), roleMiddleware(...enquiryRoles), validate(updateSchema), controller.update);
router.put('/:id', validate(idParamSchema, 'params'), roleMiddleware(...enquiryRoles), validate(updateSchema), controller.update);
router.delete('/:id', validate(idParamSchema, 'params'), roleMiddleware(...enquiryRoles), controller.remove);
export default router;
