import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes';
import hotelRoutes from '../modules/hotels/routes';
import staffRoutes from '../modules/staff/routes';
import roomTypeRoutes from '../modules/roomTypes/routes';
import roomRoutes from '../modules/rooms/routes';
import housekeepingRoutes from '../modules/housekeeping/routes';
import maintenanceRoutes from '../modules/maintenance/routes';
import guestRoutes from '../modules/guests/routes';
import leadRoutes from '../modules/leads/routes';
import enquiryRoutes from '../modules/enquiries/enquiries.routes';
import bookingRoutes from '../modules/bookings/bookings.routes';
import paymentRoutes from '../modules/payments/payments.routes';
import reviewRoutes from '../modules/reviews/reviews.routes';
import campaignRoutes from '../modules/campaigns/campaigns.routes';
import corporateLeadRoutes from '../modules/corporateLeads/corporateLeads.routes';
import eventLeadRoutes from '../modules/eventLeads/eventLeads.routes';
import whatsappRoutes from '../modules/whatsapp/whatsapp.routes';
import dashboardRoutes from '../modules/dashboard/dashboard.routes';
import analyticsRoutes from '../modules/analytics/analytics.routes';
import calendarRoutes from '../modules/calendar/calendar.routes';
import reportRoutes from '../modules/reports/reports.routes';
import taskRoutes from '../modules/tasks/tasks.routes';
import notificationRoutes from '../modules/notifications/notifications.routes';
import platformRoutes from '../modules/platform/platform.routes';
import reviewGrowthRoutes from '../modules/reviewGrowth/reviewGrowth.routes';
import hotelIntegrationRoutes from '../modules/hotelIntegrations/hotelIntegrations.routes';
import birthdayAutomationRoutes from '../modules/birthdayAutomation/birthdayAutomation.routes';
import festivalCampaignRoutes from '../modules/festivalCampaigns/festivalCampaigns.routes';
import comebackCampaignRoutes from '../modules/comebackCampaigns/comebackCampaigns.routes';
import loyaltyReferralRoutes from '../modules/loyaltyReferrals/loyaltyReferrals.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/platform', platformRoutes);
router.use('/hotels', hotelRoutes);
router.use('/staff', staffRoutes);
router.use('/room-types', roomTypeRoutes);
router.use('/rooms', roomRoutes);
router.use('/housekeeping', housekeepingRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/guests', guestRoutes);
router.use('/leads', leadRoutes);
router.use('/enquiries', enquiryRoutes);
router.use('/bookings', bookingRoutes);
router.use('/payments', paymentRoutes);
router.use('/reviews', reviewRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/corporate-leads', corporateLeadRoutes);
router.use('/event-leads', eventLeadRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/calendar', calendarRoutes);
router.use('/reports', reportRoutes);
router.use('/tasks', taskRoutes);
router.use('/notifications', notificationRoutes);
router.use('/review-growth', reviewGrowthRoutes);
router.use('/hotel-integrations', hotelIntegrationRoutes);
router.use('/birthday-automation', birthdayAutomationRoutes);
router.use('/festival-campaigns', festivalCampaignRoutes);
router.use('/comeback-campaigns', comebackCampaignRoutes);
router.use('/loyalty-referrals', loyaltyReferralRoutes);

export default router;
