import { Router } from 'express';
import { authMiddleware } from '../../middlewares/authMiddleware';
import { hotelAccessMiddleware } from '../../middlewares/hotelAccessMiddleware';
import { roleMiddleware } from '../../middlewares/roleMiddleware';
import { validate } from '../../validations/validate';
import { assignSchema, createSchema, idParamSchema, listQuerySchema, noteSchema, rescheduleSchema, statusSchema, updateSchema } from './tasks.validation';
import * as controller from './tasks.controller';

const router = Router();
const taskRoles = ['super_admin', 'hotel_owner', 'hotel_manager', 'reception_staff', 'sales_staff'] as const;
router.use(authMiddleware, hotelAccessMiddleware);
router.get('/stats', roleMiddleware(...taskRoles), controller.stats);
router.get('/', roleMiddleware(...taskRoles), validate(listQuerySchema, 'query'), controller.list);
router.post('/', roleMiddleware(...taskRoles), validate(createSchema), controller.create);
router.patch('/:id/assign', validate(idParamSchema, 'params'), roleMiddleware(...taskRoles), validate(assignSchema), controller.assign);
router.patch('/:id/status', validate(idParamSchema, 'params'), roleMiddleware(...taskRoles), validate(statusSchema), controller.updateStatus);
router.patch('/:id/reschedule', validate(idParamSchema, 'params'), roleMiddleware(...taskRoles), validate(rescheduleSchema), controller.reschedule);
router.patch('/:id/notes', validate(idParamSchema, 'params'), roleMiddleware(...taskRoles), validate(noteSchema), controller.addNote);
router.get('/:id', roleMiddleware(...taskRoles), validate(idParamSchema, 'params'), controller.getById);
router.patch('/:id', validate(idParamSchema, 'params'), roleMiddleware(...taskRoles), validate(updateSchema), controller.update);
router.put('/:id', validate(idParamSchema, 'params'), roleMiddleware(...taskRoles), validate(updateSchema), controller.update);
router.delete('/:id', validate(idParamSchema, 'params'), roleMiddleware(...taskRoles), controller.remove);
export default router;
